version: '3.8'

services:
  db:
    image: postgres:16-alpine # Using a lightweight PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: woodrose
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Load password from .env file
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data to a named volume

volumes:
  db_data: